version: '3.5'
services:
    # Database 
    mysql_db:
        container_name: 'mysql-db'
        image: mysql-db:latest
        build:
            context: ./database/
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
        - '3336:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
    # Crawler (PHP)
    crawler:
        container_name: 'crawler'
        image: crawler:latest
        restart: always
        build:
            context: ./crawler/
        volumes:
            - './crawler/src:/var/www/html'
        depends_on: 
            - 'mysql_db'
        ports:
        - '4000:80'
        environment:
            PORT: 4000
            DB_HOST: mysql_db
            DB_USER: ${MYSQL_USER}
            DB_PASS: ${MYSQL_PASSWORD}
            DB_NAME: ${MYSQL_DATABASE}
# Network to Communicate
networks:
    default:
        name: crawler-network