version: '2'
# Containers
services:
    # Crawler (PHP)
    crawler:
        container_name: 'crawler'
        image: crawler:latest
        restart: always
        build:
            context: ${BUILD_PATH}/crawler/
        volumes:
        - 'website:/var/www/html'
        ports:
        - '4000:80'
        environment:
            PORT: 4000 
# Volumes
volumes:
    website:
        driver: local
        driver_opts:
            type: none
            device: ${BUILD_PATH}/crawler/src
            o: bind
