version: '3.5'
# Containers
services:
    # Crawler (PHP)
    crawler:
        container_name: 'crawler'
        image: crawler:latest
        restart: always
        build:
            context: ${BUILD_PATH}/crawler/
        volumes:
            - type: volume
              source: website
              target: /var/www/html
        ports:
        - '4000:80'
        environment:
            PORT: 4000 
# Volumes
volumes:
    website:
        driver: local
        driver_opts:
            type: none
            device: ${BUILD_PATH}/crawler/src
            o: bind
# Network to Communicate
networks:
    default:
        name: crawler-network